skip_commits:
  files:
    - README.md

image: Visual Studio 2017

environment:
  GithubAuthToken:
    secure: PkFAZB6f1lwOR9i3Mn9mR+kQBszikFVxmrhtOGK7p/xKlVF8o/htJc9LSQDSi3bN

init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name"
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
        $env:packageVersion = "$env:APPVEYOR_REPO_TAG_NAME" 
      }
  - git config --global core.autocrlf true
 
build_script:
  - ps: ./build/build.ps1

test: off
  
artifacts:
  - path: Objectivity.TeamcityMaintenance

deploy:
  - provider: GitHub
    auth_token: $(GithubAuthToken)
    artifact: /.*\.zip/
    draft: true
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true